### ISSUE TITLE
Is this project functional?

### ISSUE THREAD

**Issue by codejamninja** [coderplex/OpenRank#30]
I can't get anything to work. It just displays a Vue.js page that says "Hello from API Server"

**Comment by duttakapil** [comment]
Hey @jamrizzi, unfortunately the core maintainers of the project have gotten busy with their lives / work and were unable to contribute further to the project. However, we have a very active [developer community](https://coderplex.org) in our city (Hyderabad, India) and are working towards building a active open source ecosystem, where people contribute to projects like these regularly. We are hosting a Open Source Day meetup once per month, to help people learn and encourage them to contribute. 

We hope the original contributors also find some time and come back to this project

**Comment by jamrizzi** [comment]
Cool, I think this should be noted in the README.md. It's confusing when the README presents it as a production-ready application.
