### ISSUE TITLE
creating a ER Diagram from Users,Contests,Programs

### ISSUE THREAD

**Issue by sannithibalaji** [coderplex/OpenRank#5]

**Comment by pbteja1998** [comment]
![openrank](https://user-images.githubusercontent.com/17903466/31040509-aaf833c2-a5a5-11e7-9042-37eb460457f2.png)


This is the initial version of schema that I created. Suggest any changes/additions, I will update it.


**Details**

- `User` can have a `Role`(either contestant, admin, test_creator).

- `Test Creator` can create one or many contests.

- A `Contest` can either be `public` or `private`.

- A `Private contest` can only be accessed by a contestant who have `contest_url` and `password` that are set by the `Test Creator`.

- A `contest_url` is a custom `url` created by the `Test Creator` which redirects to actual `Contest`.

- A `Public Contest` can be accessed by any `Contestant`.

- A `Contest` is live only when the current_time is between `login_start_time` and `login_start_time + duration`.

- A `Contestant` can only start/login to the contest between `login_start_time` and `login_start_time + login_duration`. After that no new contestants can join the contest.

- A `Contest` can have a `Question Set`.

- A `Question Set` is a set of many `Questions`.

- Each `Question` can have one or more `Test Case Sets`.

- A `Test Case Set` is a set of many `Test Cases`.

- A `Test Case` can either be hidden or non-hidden. Non-hidden test cases are considered as sample test cases that are shown to contestants.

- A `Contestant` can take many `Tests`.

- Each `Test` refers to a single `Contest`.

- A `Test` consists of a `Solution` to every `Question`.

- A `Solution` refers to a particular `Question` and consists of `input_program` given by `Contestant`.

**P.S.**  `FK` refers to Foreign Key in the uploaded diagram.

If anyone wants to add/change something, you can download the zip file attached below and edit that in `Mysql Work Bench`.

[OpenRank.mwb.zip](https://github.com/coderplex/OpenRank/files/1345963/OpenRank.mwb.zip)

**Comment by pbteja1998** [comment]
Final Version of ER diagram
![openrank](https://user-images.githubusercontent.com/17903466/31086399-5e1392e0-a7b7-11e7-8454-24fe8351e85a.png)
